server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lizebin
    username: lizebin
    password: 123456

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag
      logic-delete-value: true
      logic-not-delete-value: false
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    local-cache-scope: statement
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-enums-package: com.**.enums
  #type-handlers-package: com.**.mybatis.handler